\---- config
# Basic config options.
title: Recursion in Regex!
indent: 5
height: 22
width: 85
skip: 0

vim: vim -S ./.vimrc

vimrc: |
  set statusline=%-3f\ \ \ \ \ Recursioni\ in\ Regex\ (or:\ How\ parse\ IBM\ Datastage\ dsx\ file)
  map <C-C> 3<C-^><Ctrl-Home>
  map <C-O> 2<C-^><Ctrl-Home>
  map <C-E> 5<C-^><Ctrl-Home>
  map <C-P> 11<C-^><Ctrl-Home>
  map MSM ouse Method::Signatures::Modifiers;<Esc>
