c:\Temp\perl_modules\tidyview-1.14>cd c:\Temp\perl_modules\Padre-Plugin-FormBuilder-0.02

c:\Temp\perl_modules\Padre-Plugin-FormBuilder-0.02>cpan .
You are visiting the local directory
  '.'
  without lock, take care that concurrent processes do not do likewise.
CPAN: CPAN::SQLite loaded ok (v0.199)
Database was generated on Fri, 18 Nov 2011 10:27:08 GMT
You are visiting the local directory
  'c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.'
  without lock, take care that concurrent processes do not do likewise.
Running make for c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.
CPAN: Parse::CPAN::Meta loaded ok (v1.4401)
CPAN: CPAN::Meta loaded ok (v2.112150)
CPAN: Module::CoreList loaded ok (v2.49)

  CPAN.pm: Going to build c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.

Checking if your kit is complete...
Looks good
Writing Makefile for Padre::Plugin::FormBuilder
Writing MYMETA.yml and MYMETA.json
cp lib/Padre/Plugin/FormBuilder.pm blib\lib\Padre\Plugin\FormBuilder.pm
cp lib/Padre/Plugin/FormBuilder/Preview.pm blib\lib\Padre\Plugin\FormBuilder\Pre
view.pm
cp lib/Padre/Plugin/FormBuilder/FBP.pm blib\lib\Padre\Plugin\FormBuilder\FBP.pm
cp lib/Padre/Plugin/FormBuilder/Dialog.pm blib\lib\Padre\Plugin\FormBuilder\Dial
og.pm
cp lib/Padre/Plugin/FormBuilder/Perl.pm blib\lib\Padre\Plugin\FormBuilder\Perl.p
m
  c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.
  C:\Strawberry\c\bin\dmake.EXE -- OK
Directory 'c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.' not below C:\St
rawberry\cpan\build, will not store persistent state
Running make test
C:\Strawberry\perl\bin\perl.exe "-MExtUtils::Command::MM" "-e" "test_harness(0,
'inc', 'blib\lib', 'blib\arch')" t/*.t
t/01_compile.t .. ok
t/02_simple.t ... 1/14
#   Failed test '->dialog_super ok'
#   at t/02_simple.t line 24.
#          got: ..."o critic\x{0a}\x{0a}use 5.008005;\x{0a}use utf8;\x{0a}use st
rict;\x{0a}use "...
#       length: 995
#     expected: ..."o critic\x{0a}\x{0a}# This module was generated by Padre::Pl
"...
#       length: 1196
#     strings begin to differ at char 71 (line 5 column 1)

#   Failed test 'Dialog class compiled'
#   at t/02_simple.t line 36.

#   Failed test '->dialog_super ok'
#   at t/02_simple.t line 24.
#          got: ..."o critic\x{0a}\x{0a}use 5.008005;\x{0a}use utf8;\x{0a}use st
rict;\x{0a}use "...
#       length: 1056
#     expected: ..."o critic\x{0a}\x{0a}# This module was generated by Padre::Pl
"...
#       length: 1257
#     strings begin to differ at char 71 (line 5 column 1)

#   Failed test 'Dialog class compiled'
#   at t/02_simple.t line 36.
# Looks like you failed 4 tests of 14.
t/02_simple.t ... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/14 subtests

Test Summary Report
-------------------
t/02_simple.t (Wstat: 1024 Tests: 14 Failed: 4)
  Failed tests:  9-10, 12-13
  Non-zero exit status: 4
Files=2, Tests=19,  5 wallclock secs ( 0.06 usr +  0.13 sys =  0.19 CPU)
Result: FAIL
Failed 1/2 test programs. 4/19 subtests failed.
dmake.EXE:  Error code 132, while making 'test_dynamic'
  c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.
  C:\Strawberry\c\bin\dmake.EXE test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports c:/Temp/perl_modules/Padre-Plugin-FormBuilder-0.02/.
Running make install
  make test had returned bad status, won't install without force

c:\Temp\perl_modules\Padre-Plugin-FormBuilder-0.02>